### PR TITLE
Launcher Fixes

### PR DESCRIPTION
**Pull request by recore67**
-fixed fov slider not loading and responding properly

-added aspect ratio dropper that filters resolution box

-added fog indicator and toggle check

### CODE REVIEW

**Review by DCxDemo — CHANGES_REQUESTED** [review]
* the "noconfigfilefound" var: the idea is to provide default values if no config exists (TryGetValue function). so naturally you'll still have a value to work with. also i dont see you even use it anywhere, if so remove it altogether.

* "fovValueExist" and "unfixResSelect" doesn't seem to be used either?

* give label6 some meaningful name

* i dont quite get the idea behind the fog checkbox. the fog value reset to default is just a plain bad idea - you deliberately destroy previous user choice, so if he enables it again, he needs to change it back to his preferred option, which is some unnecessary extra hassle. also, unchecked checkbox implies like "no fog at all", but then it's 300. i mean, we could have extra patch option that would reset to 750 is Fog=false, but it dont see any gain over the solution without checkbox.

* the fog value itself, you seem to have lost the logarithmic logic here. the idea is to use logarithmic scale since the farther fog plane is from the player - the less drastic visual change is, so it is perceived unevenly. right now your middle is 750/2, original formula mapped middle to about 200.

* not your code problem, but also since you touched the fog stuff, you could refactor fog value to use ValidateRange function. also fog change could be refactored via an "OnFogChanged" event, then you can subscibe the UI side update func to options. you can use OnResolutionChanged as a reference

* aspect ratio code probably should be handled within the resolution change itself instead of additional fixup calls

* getAspectRatioOfResolution - not really a complaint, just a comment, early return here is a nicer option here since you'd skip other aspect ratios instantly instead of looping over all options. on larger lists it would save significant amount of work.

* not sure the autofov solution is good since if user deliberately chose to have some custom value and then changed aspect ratio, he loses it. maybe can adjust the value based on hardcoded default fov values (user value * (difference between old aspect and new aspect)). maybe change logic to let user select percent of change from default aspect instead of changing it directly?

**Comment by recore67** [comment]
The idea of adding a fog checkbox was to disallow accidental changes, given that it takes scroll wheel input. So checkbox is there to "lock it/unlock it". But as for resetting the value i guess it is a bad idea, will revert it back to normal for fog scale.

> not sure the autofov solution is good since if user deliberately chose to have some custom value and then changed aspect ratio, he loses it.

It would only run if the checkbox is unchecked, same idea as before. I know it would also auto when custom fov is already set and aspect ratio is changed (where on next instance its unchecked and different fov loaded) but I kept it like that to indicate the autofov for that specific res, I thought of adding a button specifically for autofov and just manualize it, that would make everything so much easier but would make UI to cluster. Eitherways it's still same way as old code.

> also, unchecked checkbox implies like "no fog at all", but then it's 300.

I agree, i could change the text from "fog scale" to "override fog"

> right now your middle is 750/2, original formula mapped middle to about 200.

I don't understand what you've mean here, can you explain further? the fog slider is still using the same code and middle for previous version was also 750/2.

> the fog value reset to default is just a plain bad idea - you deliberately destroy previous user choice, so if he enables it again, he needs to change it back to his preferred option

Now that i think about it, I guess it is a bad idea, will revert it back as normal.

As for the remaining suggestions, i will be addressing them on next commit 👍

**Comment by recore67** [comment]
upcoming changes will cause conflicts, closing this.

**Comment by DCxDemo** [comment]
i actually was going to reuse your code, but i wanted to detach resolution logic from the launcher entirely and then found out that fov didnt even work properly for lower resolutions. i just synced the local repo, includes launcher changes from this pr, but gotta revisit it again.

**Comment by recore67** [comment]
I've blindly closed this regarding #54, but also that for the time being I'll be inactive in supporting this code.

**Pull request closed without merging**
